server:
  port: 8081

spring:
  profiles:
    active: test
  application:
    name: shardingjdbc-example2
  #shardingjdbc主要配置 使用druid连接池
  shardingsphere:
    # 是否启用sharding
    enabled: true
    datasource:
      names: ds0,ds1 #数据源名称，多个以逗号隔开
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/sharding?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
        username: root
        password: admini
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/sharding2?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
        username: root
        password: admini
    props:
      #　是否显示sql
      sql-show: true
    sharding:
      # 配置广播表
      broadcast-tables: sys_config
      tables:
        sys_config:
          key-generator:
            column: id
            type: SNOWFLAKE
            props:
              worker:
                id: 1


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xh.shardingjdbc.example.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-field: deleted
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


## 日志配置
logging:
  # 默认加载resources文件夹下的logback-spring.xml 文件
  config: classpath:logback-spring.xml
  level:
    root: INFO